#! /bin/sh
### BEGIN INIT INFO
# Provides:             node
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Initscript for node.js servers/apps
# Description:          Initscript for node.js servers/apps
### END INIT INFO
DIR=/var/www/nodeserver
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DAEMON=/usr/bin/node
NODEUSER=node:node
DAEMON_ARGS=$DIR/handler/config.js
NAME=node
DESC=node-server
PIDFILE=/var/run/node-server.pid
LOGFILE=/var/log/node-server.log
NODE_PATH=$DIR/node_modules/
test -x $DAEMON || exit 0 
set -e
case "$1" in
  start)
        echo -n "Starting $DESC: "
        touch $PIDFILE
        chown $NODEUSER $PIDFILE
        if  NODE_PATH=$DIR/node_modules/ start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --make-pidfile --chuid node:node --background --exec $DAEMON -- $DAEMON_ARGS
        then
                echo "OK."
        else
                echo "failed"
        fi
        ;;
  stop)
        echo -n "Stopping $DESC: "
        if start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --chuid $NODEUSER --name $NAME
        then
                echo "OK."
        else
                echo "failed"
        fi
        rm -f $PIDFILE
        ;;
  restart|force-reload|reload)
        ${0} stop
        ${0} start
        ;;
  status)
        echo -n "$DESC is "
        if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
        then
                echo "running"
        else
                echo "not running"
        fi
        ;;
  *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status|reload}" >&2
        exit 1
        ;;
esac
exit 0
